services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ydays-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/database:/app/db
    environment:
      - NODE_ENV=development
    command: ./start.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ydays-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
